---
title: "Quiz 4"
author: "Chaeeun Shin"
date: "03/05/2024"
output: pdf_document
---

```{r}
library(tidyverse)
library(caret)
library(leaps)
library(bestglm)
library(MASS)
```
#Part 1
```{r}
data1 <- read.csv("Ames_Housing_Data.csv")
data1$CentralAir <- ifelse(data1$CentralAir=='Y',1,0)
str(data1)
```

#1-1. Splitting training and testing data
```{r}
set.seed(123)
training_samples <- data1$SalePrice %>%
  createDataPartition(p=.75,list=FALSE)
train_data <- data1[training_samples,]
test_data <- data1[-training_samples,]
nrow(train_data)
nrow(test_data)
```

#1-2. Stepwise variable selection
```{r}
full <- lm(SalePrice~., data=train_data)
null <- lm(SalePrice~1, data=train_data)
n = nrow(train_data)
bestmodel1 <- stats::step(null,scope=list(lower=null,upper=full),direction='both',k=log(n))
bestmodel1$call
bestmodel1$coefficients
```

#1-2. Prediction: bestmodel1
```{r}
pred1 <- predict(bestmodel1,newdata=test_data)
rmse1 <- sqrt(mean((pred1-test_data$SalePrice)^2))
r_squared1 <- cor(test_data$SalePrice,pred1)^2
print(paste("RMSE: ",rmse1))
print(paste("R^2: ",r_squared1))
```

#1-3. Best subset selection
```{r}
bestmodel2 <- regsubsets(SalePrice~., data=train_data,nvmax=ncol(train_data)-1,method="exhaustive")
bestmodel2_summary <- summary(bestmodel2)
bestmodel2_size <- which.min(bestmodel2_summary$rss)
coef(bestmodel2,id=bestmodel2_size)
bestmodel2_formula <- as.formula(paste("SalePrice~",paste(names(coef(bestmodel2,id=bestmodel2_size))[-1],collapse="+")))
print(bestmodel2_formula)
```

#1-3. Prediction: bestmodel2
```{r}
fitted_model <- lm(bestmodel2_formula, data=train_data)
pred2 <- predict(fitted_model, test_data)
rmse2 <- sqrt(mean((pred2-test_data$SalePrice)^2))
r_squared <- cor(test_data$SalePrice,pred2)^2
print(paste("RMSE: ",rmse2))
print(paste("R^2: ",r_squared))
```

#1-4. Compare BIC : Smaller BIC is better
```{r}
(bic1 <- BIC(bestmodel1))
(bic2 <- BIC(fitted_model))
```

#Part 2.
#2-1. 
```{r}
data2 <- read.csv("Titanic2.csv")
data2 <- data2[,-c(1,4,9,11)]
data2 <- data2[!is.na(data2$Age),]
cat("There are",nrow(data2),"passengers left.")
```

#2-2.
```{r}
str(data2)
data2$Survived <- as.factor(data2$Survived)
data2$Pclass <- as.factor(data2$Pclass)
```

#2-3.
```{r}
set.seed(123)
training_samples <- data2$Survived %>%
  createDataPartition(p=0.8,list=FALSE)
train_data <- data2[training_samples,]
test_data <- data2[-training_samples,]
nrow(train_data)
nrow(test_data)
```

#2-4.
```{r}
log_model <- glm(Survived~., data=train_data, family=binomial)
summary(log_model)
```

#2-5
```{r}
probabilities <- log_model %>%
  predict(test_data, type="response")
log_pred <- as.factor(ifelse(probabilities>0.5,1,0))
confusionMatrix(log_pred,test_data$Survived,positive='1')
```

#2-6
```{r}
new <- test_data[1,]
new$Pclass <- '3'
new$Sex <- 'male'
new$Age <- 23
new$SibSp <- 0
new$Fare <- 8.25
new$Embarked <- 'Q'
p <- log_model %>%
  predict(new, type='response')
ifelse(p>0.5,'Survived','Not survived')
```