---
title: Quiz 8
author: Chaeeun Shin
date: 04/08/2024
output: pdf_document
---

```{r}
library(dplyr)
library(caret)
library(randomForest)
```

#1
```{r}
GreatUnknown <- read.csv("GreatUnknown.csv")
GreatUnknown <- na.omit(GreatUnknown)
cat("There are ",nrow(GreatUnknown),"cases left.")
GreatUnknown$y <- as.factor(GreatUnknown$y)

set.seed(123)
training.samples <- GreatUnknown$y %>%
  createDataPartition(p=0.75,list=FALSE)
train.data <- GreatUnknown[training.samples,]
test.data <- GreatUnknown[-training.samples,]
nrow(train.data)
nrow(test.data)
```

#2
```{r}
set.seed(123)
model <- train(y~., data=train.data, method="rf",trControl=trainControl("cv",number=10), importance=TRUE)
model$bestTune
model$finalModel
cat("Sensitivity: ", 1190/(1190+170),"\n")
cat("Specificity: ", 1974/(1974+117),"\n")
cat("Accuracy: ", (1974+1190)/(1974+117+170+1190),"\n")
```
#3
```{r}
pred <- model %>% predict(test.data)
table(pred,test.data$y)
cat("Sensitivity: ",389/(49+389),"\n")
cat("Specificity: ",648/(64+648),"\n")
cat("Accuracy: ",(648+389)/(64+648+49+389),"\n")
```
#4: plot MeanDecreaseAccuracy
```{r}
varImpPlot(model$finalModel, type=1)
```

#4: plot MeanDecreaseGini
```{r}
varImpPlot(model$finalModel, type=2)
```
#5
```{r}
varImp(model, type=1)
```

#Part II
#1
```{r}
QuestionMark <- read.csv("QuestionMark.csv")
QuestionMark <- na.omit(QuestionMark)
cat("There are", nrow(QuestionMark), "observations left.")

set.seed(123)
training.samples <- QuestionMark$y %>%
  createDataPartition(p=0.95,list=FALSE)
train.data <- QuestionMark[training.samples,]
test.data <- QuestionMark[-training.samples,]
nrow(train.data)
nrow(test.data)
```

#2
```{r}
model <- train(y~., data=train.data, method="rf",trControl=trainControl("cv",number=10))
model$bestTune
```

#3
```{r}
predictions <- model %>% predict(test.data)
cat("RMSE: ", RMSE(predictions, test.data$y))
```

#4
```{r}
set.seed(123)
rf <- randomForest(y~., data=QuestionMark, ntree=500, mtry=8, keep.forest=FALSE, importance=TRUE)
sqrt(rf$mse[500])
importance(rf)
varImpPlot(rf)
```
```