---
title: Quiz 9
author: Chaeeun Shin
date: 4/16/2024
output: pdf_document
---

```{r}
library(caret)
library(neuralnet)
library(randomForest)
library(rpart)
library(rattle)
library(MASS)
library(tidyverse)
library(glmnet)
library(leaps)
library(ggplot2)
```

1.
(a)
```{r}
GreatUnknown <- read.csv("GreatUnknown.csv")
GreatUnknown <- na.omit(GreatUnknown)
data <- scale(GreatUnknown[-13])
pc <- princomp(data,cor=TRUE)
```

(b)
```{r}
library(factoextra)
fviz_eig(pc)
```

**K-means fit**
```{r}
k.means.fit <- kmeans(data,2)
library(cluster)
clusplot(data,k.means.fit$cluster,main="2D representation of the Cluster solution",color=TRUE,shade=TRUE,labels=2,lines=0)
table(k.means.fit$cluster, GreatUnknown$y)
# accuracy = (2643+913)/4601
```

**H.ward**
```{r}
d <- dist(data,method="euclidean")
H.fit <- hclust(d,method="ward.D")
plot(H.fit)
rect.hclust(H.fit,k=2,border="red")
groups <- cutree(H.fit,k=2)
clusters <- factor(groups,levels=1:2,labels=c(0,1))
clusplot(data,groups,main="2D representation of the Cluster solution",color=TRUE,shade=TRUE,labels=2,lines=0)
table(GreatUnknown$y,clusters)
# accuracy = (2621+754)/4601
```

**H.Average**
```{r}
H.fit <- hclust(d,method="average")
plot(H.fit)
rect.hclust(H.fit,k=2,border="red")
groups <- cutree(H.fit,k=2)
clusters <- factor(groups,levels=1:2,labels=c(0,1))
clusplot(data,groups,main="2D representation of the Cluster solution",color=TRUE,shade=TRUE,labels=2,lines=0)
table(GreatUnknown$y,clusters)
# accuracy = (2788+1)/4601
```

**Comparison: K-means>H.ward>H.average Based on their accuracy on confusion matrix. **

2. 
```{r}
library(devtools)
library(ggbiplot)
```

(a)
```{r}
GreatUnknown.pca <- prcomp(data,center=TRUE,scale.=TRUE)
summary(GreatUnknown.pca)
```
By the row "Proportion of Variance", we can find what percentage of the variations each PC would explain. 

(b)
```{r}
ggbiplot(GreatUnknown.pca)
```

(c)
```{r}
ggbiplot(GreatUnknown.pca, ellipse=TRUE, groups=GreatUnknown$y)
```

(d)
```{r}
GreatUnknown.pca$rotation[,1]
```
**PC1 contains parts of each w1~w12 that accounts for the greatestt possible variance. ** 