---
title: Quiz 7
author: Chaeeun Shin
date: 4/9/2021
output: pdf_document
---
```{r}
if(!requireNamespace("tidyverse")) install.packages("tidyverse")
library(MASS)
library(tidyverse)
library(caret)
library(glmnet)
library(caTools)
```
#1
```{r}
AmesHousing <- read.csv("Ames_Housing_Data.csv")
AmesHousing <- na.omit(AmesHousing)
cat("There are", nrow(AmesHousing),"observations left.")
```

#2
```{r}
set.seed(123)
training.samples <- AmesHousing$SalePrice %>%
  createDataPartition(p=0.75,list=FALSE)
train.data <- AmesHousing[training.samples,]
test.data <- AmesHousing[-training.samples,]
nrow(train.data)
nrow(test.data)
```

#3 Ridge regression
```{r}
x <- model.matrix(SalePrice~., data=train.data)[,-1]
# create a matrix by expanding factors to a set of dummy variables
y <- train.data$SalePrice
cv <- cv.glmnet(x,y,alpha=0)
cat("The best lambda value: ", cv$lambda.min)
ridgemodel <- glmnet(x,y,alpha=0,lambda=cv$lambda.min)
coef(ridgemodel) #coefficient of the fitted model
x.test <- model.matrix(SalePrice~., data=test.data)[,-1]
predictions <- ridgemodel %>% predict(x.test) %>% as.vector() #making predictions
data.frame(
  RMSE = RMSE(predictions, test.data$SalePrice),
  Rsquare = R2(predictions, test.data$SalePrice)
)
plot(x=test.data$SalePrice, y=predictions)
abline(1,1)  #plot
```

#4
```{r}
cv <- cv.glmnet(x,y,alpha=1)
cat("The best lambda value: ",cv$lambda.min)
lassomodel <- glmnet(x,y,alpha=1,lambda=cv$lambda.min)
coef(lassomodel) #coefficient of the fitted model
predictions <- lassomodel %>% predict(x.test) %>% as.vector()
data.frame(
  RMSE = RMSE(predictions,test.data$SalePrice),
  Rsquare = R2(predictions,test.data$SalePrice)
)
plot(x=test.data$SalePrice,y=predictions)
abline(0,1)
```

#5
```{r}
elasticnetmodel <- train(SalePrice~., data=train.data, method="glmnet",trControl=trainControl("cv",number=10),tuneLength=10)
elasticnetmodel$bestTune
coef(elasticnetmodel$finalModel, elasticnetmodel$bestTune$lambda)

model <- glmnet(x,y,alpha=0.1,lambda=849.1096)
predictions <- model %>% predict(x.test) %>% as.vector()
data.frame(
  RMSE = RMSE(predictions, test.data$SalePrice),
  Rsquare = R2(predictions, test.data$SalePrice)
)
plot(x=test.data$SalePrice, y=predictions)
abline(1,1)
```
